
import { byValueKey, byText } from 'appium-flutter-finder'; 

 

export const selectors = { 
    employeeField: byValueKey('employeeIdField'), 
    passwordField: byValueKey('passwordField'), 
    checkbox: byValueKey('termsCheckbox'), 
    loginButton: byValueKey('loginButton'), 
    draftLoans: byValueKey('draftLoans'), 
    appliedLoans: byValueKey('appliedLoans'), 
    submittedLoans: byValueKey('submittedLoans'), 
    searchLoans: byValueKey('searchLoan'), 
    searchLoansBM: byValueKey('searchLoanBM'), 
    searchLoansCO: byValueKey('searchLoanCO'), 
    loanDetails: byText('LOAN DETAILS'), 
    customerInformation: byValueKey('customerInformation'), 
    customerInformationReapplied: byValueKey('customerInformationReapplied'), 
    nextButton: byText('NEXT'), 
    nextSmallButton: byText('Next'), 
    continueButton: byText('Continue'), 
    continueCapsButton: byText('CONTINUE'), 
    educationField: byValueKey('educationalQualification'), 
    occupationField: byValueKey('occupation'), 
    occupationDetails: byValueKey('occupationDetails'), 
    captureButton: byValueKey('captureButton'), 
    udyamNumberField: byValueKey('udyogAadharNumberController'), 
    verifyButton: byText('Verify'), 
    verifyPhone:byValueKey('verifyPhone'), 
    businessTypeDropdown: byValueKey('businessTypeController'), 
    enterpriseNameField: byValueKey('enterpriseNameController'), 
    businessDescriptionField: byValueKey('businessDescriptionController'), 
    sameAddressCheckbox: byValueKey('sameAddressCheckbox'), 
    addressLine1Field: byValueKey('addressLine1Controller'), 
    addressLine2Field: byValueKey('addressLine2Controller'), 
    stateDropdown: byValueKey('stateController'), 
    cityDropdown: byValueKey('cityController'), 
    pinCodeField: byValueKey('zipCodeController'), 
    yearOfEstablishmentField: byValueKey('yearOfEstablishmentController'), 
    accountNumberField: byValueKey('accountNoController'), 
    bankNameField: byValueKey('banknameController'), 
    ifscCodeField: byValueKey('ifscController'), 
    branchNameField: byValueKey('branchnameController'), 
    uploadTile: byValueKey('cheque'), 
    loanTenure: byValueKey('loanTenure'), 
    okButton: byText('Ok'), 
    panInput: byValueKey('panInput'), 
    confirmSubmitButton: byText('CONFIRM AND SUBMIT LOAN'), 
    phoneInput:byValueKey('phoneInput'), 
    panDocument: byValueKey('panDocument'), 
    otpField : byValueKey('passcodeField'), 
    verifyOTP : byValueKey('verifyOTP'), 
    addDocument:byValueKey('addDocument'), 
    addButton: byValueKey('addButton'), 
    documents: byValueKey('documents'), 
    selectDocuments:byValueKey('selectDocuments'), 
    documentNumber: byValueKey('documentNumber'), 
    frontSide:byValueKey('frontSide'), 
    backSide:byValueKey('backSide'), 
    newLoan: byText('START NEW LOAN'), 
    noCapsButton: byText('NO'), 
    showDialog:byValueKey('showDialog'), 
 
    //start new loan 
    loanType:byValueKey('loanType'), 
    loanPurpose: byValueKey('loanPurpose'), 
    loanAmount:byValueKey('loanAmount'), 
    preferredChannel: byValueKey('preferredChannel'), 
    loanCenter:byValueKey('loanCenter'), 
    loanDate: byValueKey('loanDate'), 
    ownHouse:byText('Living in own house'), 
    noOfYears: byValueKey('noOfYears'), 
    squareFeet: byValueKey('squareFeet'), 
    tiledHouse: byText('Tiled House'), 
    noOfMembers:byValueKey('noOfMembers'), 
    ownBuilding: byText('Business in own building'), 
    businessYear: byValueKey('businessYear'), 
    businessMonth: byValueKey('businessMonth'), 
    partnership: byText('Partnership'), 
    soleOwnership: byText('Sole ownership'), 
    proceedOTP: byText('PROCEED WITH OTP'), 
    aadhaarNumber: byValueKey('aadhaarNumber'), 
    aadhaarFrontSide:byValueKey('aadhaarFrontSide'), 
    aadhaarBackSide: byValueKey('aadhaarBackSide'), 
    coborrowerAadhaarNumber: byValueKey('coborrowerAadhaarNumber'), 
    coborrowerAadhaarFrontSide:byValueKey('coborrowerAadhaarFrontSide'), 
    coborrowerAadhaarBackSide: byValueKey('coborrowerAadhaarBackSide'), 
    retake:byText('RETAKE'), 
    camera:byText('Camera'), 
    capture: byText('Capture'), 
    otpInput: byValueKey('otpInput'), 
    dueCollection : byValueKey('dueCollection'), 
  dueCollectionBtn : byValueKey('DueCollectionButton'), 
  allDues : byValueKey('allDues'), 
  searchDue : byValueKey("searchDue"), 
  completeBtn : byValueKey("completeBtn"), 
  confirm1 : byValueKey("confirmOne"), 
  confirm2 : byValueKey("confirmTwo"), 
  confirm3 : byValueKey("confirmThree"), 
  proceedButton : byValueKey("proceedButton"), 
  bankTransfer:byText('Bank Transfer'), 
  uploadDocument: byText('Upload Document'), 
  gallery:byText('Gallery'), 
  digitalPayment :byText('Digital Payment'), 
  generateQR: byText('GENERATE QR'), 
  otherAmountSwitch: byValueKey('otherAmountSwitch'), 
  walletSwitch: byValueKey('walletSwitch'), 
  otherAmountField: byValueKey('otherAmountField'), 
  closeIcon: byValueKey('closeIcon'), 
  clearIcon: byValueKey('clearIcon'), 
  profileIcon:byValueKey('profileIcon'), 
  profileBackButton: byValueKey('profileBackButton'), 
  filterIcon: byValueKey('filterIcon'), 
  thisMonth: byText('This Month'), 
  lastMonth: byText('Last Month'), 
  thisQuarter: byText('This Quarter'), 
  thisYear: byText('This Year'), 
  dateRange: byText('Date Range'), 
  fromDate: byValueKey('fromDate'), 
  toDate: byValueKey('toDate'), 
  menuIcon: byValueKey('menuIcon'), 
  dashboardText: byText('Dashboard'), 
  myprofileText: byText('My Profile'), 
  customersText: byText('Customers'), 
  loansText: byText('Loans'), 
  signOut: byText('Sign Out'), 
  applicantOwnCheckbox: byValueKey('applicantCheckbox'), 
  monthlyIncome: byValueKey('businessIncome'), 
  familyMemberMonthlyIncome: byValueKey('familyMemberBusinessIncome'), 
  monthlyRevenue: byValueKey('monthlyRevenue'), 
  setTarget: byText('Set Target'), 
  selectCRO: byValueKey('selectCRO'), 
  selectFinancialYear: byValueKey('selectFinancialYear'), 
  selectMonth: byValueKey('selectMonth'), 
  targetAmount: byValueKey('targetAmount'), 
  cashRecievedText: byText('CASH RECEIVED'), 
  agricultureType: byValueKey('agricultureType'), 
  agricultureAcre: byValueKey('agricultureArea'), 
  agricultureLand: byValueKey('agricultureLand'), 
  agricultureDetails: byValueKey('agricultureDetails'), 
  agricultureProof: byValueKey('agricultureProof'), 
  depositAmountText: byText('DEPOSIT AMOUNT'), 
  depositAmount: byValueKey('depositAmount'), 
  //acknowledgeText: byText('ACKNOWLEDGE'), 
  acknowledgeText: byValueKey('acknowledgeButton'), 
  // rejectText: byText('REJECT'), 
  rejectText: byValueKey('rejectButton'), 
  sendAcknowledgeText: byText('SEND ACKNOWLEDGE'), 
  confirmText: byText('CONFIRM'), 
  cashOnHandList: byValueKey('cashOnHandList'), 
  submitButton: byText('SUBMIT'), 
  notificationIcon:byValueKey('notificationIcon'), 
  incomeDetails: byValueKey('incomeDetails'), 
  searchLoansReapplied: byValueKey('searchLoansReapplied'), 
  searchLoansResubmit:byValueKey('searchLoansResubmit'), 
  updateDetails: byText('UPDATE DETAILS'), 
  popupMenu:byValueKey('popupMenu'), 
  popupMenuEdit:byValueKey('popupEdit'), 
  panInputCoborrower: byValueKey('panInputCoborrower'), 
  verifyPhoneCoborrower:byValueKey('verifyPhoneCoborrower'), 
  phoneInputCoborrower:byValueKey('phoneInputCoborrower'), 
  panDocumentCoborrower: byValueKey('panDocumentCoborrower'), 
  additionalInsuredCheckbox: byValueKey('additionalInsuredCheckbox'), 
  familyMemberLocation:byValueKey('familyMemberLocation'), 
  familyMemberRelationship:byValueKey('familyMemberRelationship'), 
  familyMemberEducation:byValueKey('familyMemberEducation'), 
  familyMemberOccupation:byValueKey('familyMemberOccupation'), 
  familyMemberOccupationDetails:byValueKey('familyMemberOccupationDetails'), 
  aadhaarOtpInput: byValueKey('aadhaarOtpInput'),

  // --- BM Loan Resubmission flow ---
  // Dashboard tile text confirmed via native page source: "ReSubmitted".
  resubmittedLoans: byText('ReSubmitted'),
  basicEligibilityCheck: byText('BASIC ELIGIBILITY CHECK'),
  loanSummary: byText('LOAN SUMMARY'),

}